name: Publicar arquivos Power BI

on:
  push:
    branches:
      - main
    paths:
      - 'pbix-files/**/*.pbix'
  workflow_dispatch:  # Permite execução manual

jobs:
  deploy-powerbi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Instalar PowerBI CLI
        run: |
          npm install -g powerbi-cli

      - name: Listar arquivos PBIX
        id: find-pbix
        run: |
          echo "Verificando arquivos PBIX"
          mkdir -p pbix-files
          FILES=$(find pbix-files -name "*.pbix" | tr '\n' ' ')
          echo "Arquivos encontrados: $FILES"
          echo "files=$FILES" >> $GITHUB_OUTPUT
      
      - name: Autenticar e publicar no Power BI
        if: steps.find-pbix.outputs.files != ''
        run: |
          # Criar arquivo de configuração para autenticação
          cat > config.json << EOF
          {
            "clientId": "${{ secrets.CLIENT_ID }}",
            "clientSecret": "${{ secrets.CLIENT_SECRET }}",
            "tenantId": "eaaf39f1-6f65-42cc-bfe2-b9c336aaf2a2"
          }
          EOF
          
          # Autenticar usando App Registration
          powerbi login --config config.json
          
          # Publicar cada arquivo PBIX encontrado
          for file in ${{ steps.find-pbix.outputs.files }}; do
            echo "Publicando arquivo: $file"
            powerbi import -w "37ac69ab-ad7a-4540-af1d-baa525ee3c7f" -f "$file" --nameConflict Overwrite
            echo "Publicação concluída: $file"
          done
