name: Publicar arquivos Power BI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup PowerShell e diretório
      shell: pwsh
      run: |
        Write-Host "Versão do PowerShell: $($PSVersionTable.PSVersion)"
        # Criar diretório pbix-files se não existir
        if (-not (Test-Path "pbix-files")) {
          New-Item -Path "pbix-files" -ItemType Directory -Force
          Write-Host "Diretório pbix-files criado"
        }
        
        # Listar estrutura do repositório
        Get-ChildItem -Recurse -Depth 2 | Select-Object FullName
    
    - name: Instalar módulo PowerBI (método alternativo)
      shell: pwsh
      run: |
        # Atualizar o PSGallery sem depender do NuGet
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        
        # Definir PSGallery como confiável
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        
        # Instalar PowerShellGet
        Write-Host "Instalando PowerShellGet..."
        Install-Module PowerShellGet -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck
        
        # Instalar módulo PowerBI
        Write-Host "Instalando módulo MicrosoftPowerBIMgmt..."
        Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck
        
        Write-Host "Verificando módulos instalados:"
        Get-Module -Name MicrosoftPowerBIMgmt* -ListAvailable | Format-Table Name, Version
    
    - name: Deploy to Power BI
      shell: pwsh
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: "eaaf39f1-6f65-42cc-bfe2-b9c336aaf2a2"
        WORKSPACE_ID: "37ac69ab-ad7a-4540-af1d-baa525ee3c7f"
      run: |
        Write-Host "Iniciando processo de publicação..."
        
        try {
          # Criar credencial segura
          $password = ConvertTo-SecureString $env:CLIENT_SECRET -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($env:CLIENT_ID, $password)
          
          # Conectar ao Power BI
          Write-Host "Conectando ao Power BI Service..."
          Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -TenantId $env:TENANT_ID
          
          # Procurar arquivos PBIX no repositório
          Write-Host "Procurando arquivos PBIX..."
          $files = Get-ChildItem -Path "." -Recurse -Filter "*.pbix" -File
          
          if ($files.Count -eq 0) {
            Write-Host "⚠️ Nenhum arquivo PBIX encontrado no repositório"
            exit 0
          }
          
          Write-Host "🔍 Encontrados $($files.Count) arquivos PBIX para publicação:"
          $files | ForEach-Object { Write-Host " - $($_.FullName)" }
          
          # Publicar cada arquivo
          foreach ($file in $files) {
            $fileName = $file.Name
            $filePath = $file.FullName
            
            Write-Host "📤 Publicando arquivo: $fileName"
            try {
              New-PowerBIReport -Path $filePath -WorkspaceId $env:WORKSPACE_ID -ConflictAction CreateOrOverwrite
              Write-Host "✅ Arquivo $fileName publicado com sucesso!"
            } catch {
              Write-Host "❌ Erro ao publicar $fileName"
              Write-Host "Detalhes do erro: $_"
              # Continue para o próximo arquivo mesmo se houver erro
            }
          }
          
          Write-Host "🎉 Processo de publicação concluído!"
        } catch {
          Write-Host "❌ Erro geral na execução do script: $_"
          exit 1
        }
